ALIASES = {
    "tomatoes": "tomato",
    "cherry tomatoes": "tomato",
    "roma tomatoes": "tomato",
    "tomato sauce": "tomato sauce",
    "tomato sauces": "tomato sauce",

    "onions": "onion",
    "red onions": "red onion",
    "yellow onions": "onion",
    "white onions": "onion",
    "green onions": "green onion",
    "scallions": "green onion",

    "garlic cloves": "garlic",
    "cloves garlic": "garlic",
    "minced garlic": "garlic",

    "ground beef": "beef",
    "minced beef": "beef",
    "beef mince": "beef",
    "ground turkey": "turkey",
    "ground chicken": "chicken",
    "ground pork": "pork",

    "italian sausage": "sausage",
    "hot italian sausage": "sausage",
    "mild italian sausage": "sausage",
    "breakfast sausage": "sausage",

    "chicken breast": "chicken",
    "chicken breasts": "chicken",
    "chicken thigh": "chicken",
    "chicken thighs": "chicken",
    "shredded chicken": "chicken",

    "bell peppers": "bell pepper",
    "red pepper": "bell pepper",
    "green pepper": "bell pepper",
    "yellow pepper": "bell pepper",
    "orange pepper": "bell pepper",
    "peppers": "bell pepper",
    "jalapenos": "jalapeno",

    "potatoes": "potato",
    "sweet potatoes": "sweet potato",

    "eggs": "egg",
    "tortillas": "tortilla",
    "corn tortillas": "tortilla",
    "flour tortillas": "tortilla",

    "limes": "lime",
    "lemons": "lemon",

    "beans": "bean",
    "black beans": "black bean",
    "kidney beans": "kidney bean",
    "white beans": "white bean",
    "pinto beans": "bean",
